export const INITIAL_SETTINGS = {
  requestURL: "",
  keyList: [],
  selectedChartType: "Bar",
  primaryAxisKey: "",
  primaryAxisMin: -Infinity,
  primaryAxisMax: Infinity,
  primaryAxisKeyType: "",
  secondaryAxisKey: "",
  secondaryAxisMin: -Infinity,
  secondaryAxisMax: Infinity,
  secondaryAxisKeyType: "",
  colorKey: undefined,
  colorRange: [],
  parentKey: "_root_",
  graphHeight: 450,
  graphWidth: 800,
  title: "",
  description: "",
  note: "",
  footer: "",
  showTicks: true,
  showLabels: true,
  showValues: false,
  showKeys: true,
  showTooltips: true,
  labelPositionInside: true,
  gridColor: "#eeeeee",
  labelColor: "#212121",
  baseColor: "#5682a3",
  backgroundColor: "#ffffff",
  reverse: false,
  sort: false,
  useKeys: false,
  keysToUse: [],
  labelsArray: [],
  rotateLabel: true,
  tickFormat: "none",
  barPadding: 10,
  roundedCorner: 0,
  markOpacity: 1,
  markRadius: 3,
  mouseOverValueFormat: "none",
  mouseOverValueSuffix: undefined,
  mouseOverValuePrefix: undefined,
  mouseOverLabelFormat: "none",
  mouseOverLabelSuffix: undefined,
  mouseOverLabelPrefix: undefined,
};

export const CHART_PROPERTIES: any = {
  Bar: {
    xAxes:["string", "dateTime"],
    formatXAxes: false,
    yAxes:["number", "string", "array"],
    formatYAxes: true,
    title: true,
    description: true,
    note: true,
    footer: true,
    sortBars: true,
    reverseOrder: true,
    showKeys: true,
    spacingBetweenBars: true,
    showTicks: true,
    gridColor: true,
    labelColor: true,
    roundedCorners: true,
    markRadius: false,
    tickFormat: true,
    markOpacity: true,
    xAxesTicks:{
      showLabels:true,
      settings: true,
      tickFormat: false,
      rotateLabel: true,
      showLabelInside:false,
    },
    yAxesTicks:{
      settings: true,
      tickFormat: true,
      showLabelInside:true,
    },
    mouseOver:{
      value: {
        suffix: true,
        prefix: true,
        format: true,
      },
      label: {
        suffix: true,
        prefix: true,
        format: false,
      }
    },
    backgroundColor: true,
    baseColor: true,
  },
  "Scatter Plot": {
    xAxes:["number","string", "dateTime"],
    formatXAxes: true,
    yAxes:["number", "string", "array"],
    formatYAxes: true,
    title: true,
    description: true,
    note: true,
    footer: true,
    sortBars: false,
    reverseOrder: false,
    showKeys: true,
    spacingBetweenBars: false,
    showTicks: true,
    gridColor: true,
    labelColor: true,
    roundedCorners: false,
    tickFormat: true,
    markRadius: true,
    markOpacity: true,
    xAxesTicks:{
      showLabels:true,
      settings: true,
      tickFormat: true,
      rotateLabel: true,
      showLabelInside:false,
    },
    yAxesTicks:{
      settings: true,
      tickFormat: true,
      showLabelInside:true,
    },
    mouseOver:{
      value: {
        suffix: true,
        prefix: true,
        format: true,
      },
      label: {
        suffix: true,
        prefix: true,
        format: false,
      }
    },
    backgroundColor: true,
    baseColor: true,
  }
}

export const TICK_FORMAT_OPTIONS = [
  {
    value: "none",
    text: "123456.789 (No Format)",
  },
  {
    value: "usFormat",
    text: "123 456.789 (US format)",
  },
  {
    value: "euFormat",
    text: "123 456,789 (EU format)",
  },
  {
    value: "siUs",
    text: "123.45K (US Format)",
  },
  {
    value: "siEu",
    text: "123,45K (EU Format)",
  },
  {
    value: "CurrencyUs",
    text: "$ 123 456.789 (US format)",
  },
  {
    value: "CurrencyEu",
    text: "123 456,789 € (EU format)",
  },
  {
    value: "siCurrencyUs",
    text: "$ 123.4K (US Format)",
  },
  {
    value: "siCurrencyEu",
    text: "123,4K € (EU Format)",
  },
  {
    value: "percentUs",
    text: "12.34% (US Format)",
  },
  {
    value: "percentEu",
    text: "12,34% (EU Format)",
  },
];